# Generated by Django 6.0 on 2026-01-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_production_productionmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
