# Generated by Django 6.0 on 2026-01-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_materialpurchase_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('wb_shipment_number', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_from', to='core.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_to', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentLogistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.wbshipment')),
            ],
        ),
    ]
