# Generated by Django 6.0 on 2026-01-02 20:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wbshipment_shipmentlogistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='materialpurchase',
            options={'ordering': ['-date'], 'verbose_name': 'Закупка материала', 'verbose_name_plural': 'Закупки материалов'},
        ),
        migrations.AlterModelOptions(
            name='materialstock',
            options={'verbose_name': 'Остаток материала', 'verbose_name_plural': 'Остатки материалов'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productbom',
            options={'verbose_name': 'Рецептура', 'verbose_name_plural': 'Рецептуры'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['-date'], 'verbose_name': 'Производство', 'verbose_name_plural': 'Производства'},
        ),
        migrations.AlterModelOptions(
            name='productionmaterial',
            options={'verbose_name': 'Списание материала', 'verbose_name_plural': 'Списания материалов'},
        ),
        migrations.AlterModelOptions(
            name='productstock',
            options={'verbose_name': 'Остаток продукции', 'verbose_name_plural': 'Остатки продукции'},
        ),
        migrations.AlterModelOptions(
            name='shipmentlogistics',
            options={'verbose_name': 'Логистика отгрузки', 'verbose_name_plural': 'Логистика отгрузок'},
        ),
        migrations.AlterModelOptions(
            name='wbshipment',
            options={'ordering': ['-date'], 'verbose_name': 'Отгрузка на WB', 'verbose_name_plural': 'Отгрузки на WB'},
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='material',
            name='min_stock',
            field=models.FloatField(default=0, verbose_name='Минимальный запас'),
        ),
        migrations.AddField(
            model_name='materialpurchase',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер накладной'),
        ),
        migrations.AddField(
            model_name='materialstock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена продажи'),
        ),
        migrations.AddField(
            model_name='production',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В производстве'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='completed', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='shipmentlogistics',
            name='actual_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая доставка'),
        ),
        migrations.AddField(
            model_name='shipmentlogistics',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='Ориентировочная доставка'),
        ),
        migrations.AddField(
            model_name='shipmentlogistics',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата забора'),
        ),
        migrations.AddField(
            model_name='wbshipment',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готов к отправке'), ('sent', 'Отправлен'), ('delivered', 'Доставлен на WB'), ('accepted', 'Принят WB'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('raw', 'Сырьё'), ('pack', 'Упаковка'), ('other', 'Прочее')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='date',
            field=models.DateField(verbose_name='Дата закупки'),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='materialstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='materialstock',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='materialstock',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wb_article',
            field=models.CharField(blank=True, max_length=50, verbose_name='Артикул WB'),
        ),
        migrations.AlterField(
            model_name='productbom',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='productbom',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productbom',
            name='qty_per_unit',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Количество на единицу'),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(verbose_name='Дата производства'),
        ),
        migrations.AlterField(
            model_name='production',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location', verbose_name='Локация производства'),
        ),
        migrations.AlterField(
            model_name='production',
            name='produced_qty',
            field=models.FloatField(verbose_name='Количество произведено'),
        ),
        migrations.AlterField(
            model_name='production',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productionmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='productionmaterial',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.production', verbose_name='Производство'),
        ),
        migrations.AlterField(
            model_name='productionmaterial',
            name='quantity_used',
            field=models.FloatField(verbose_name='Количество использовано'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='shipmentlogistics',
            name='carrier',
            field=models.CharField(max_length=100, verbose_name='Перевозчик'),
        ),
        migrations.AlterField(
            model_name='shipmentlogistics',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='shipmentlogistics',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='core.wbshipment', verbose_name='Отгрузка'),
        ),
        migrations.AlterField(
            model_name='shipmentlogistics',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Трек-номер'),
        ),
        migrations.AlterField(
            model_name='wbshipment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='wbshipment',
            name='date',
            field=models.DateField(verbose_name='Дата отгрузки'),
        ),
        migrations.AlterField(
            model_name='wbshipment',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_from', to='core.location', verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='wbshipment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='wbshipment',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='wbshipment',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_to', to='core.location', verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='wbshipment',
            name='wb_shipment_number',
            field=models.CharField(max_length=50, verbose_name='Номер поставки WB'),
        ),
    ]
