# Generated by Django 6.0 on 2026-01-02 20:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_location_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materialpurchase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materialstock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productbom',
            options={},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productionmaterial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productstock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shipmentlogistics',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wbshipment',
            options={},
        ),
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.RemoveField(
            model_name='material',
            name='min_stock',
        ),
        migrations.RemoveField(
            model_name='materialpurchase',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='materialstock',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='production',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='production',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='shipmentlogistics',
            name='actual_delivery',
        ),
        migrations.RemoveField(
            model_name='shipmentlogistics',
            name='estimated_delivery',
        ),
        migrations.RemoveField(
            model_name='shipmentlogistics',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='wbshipment',
            name='status',
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('raw', 'Сырьё'), ('pack', 'Упаковка'), ('other', 'Прочее')], max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material'),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='supplier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materialstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AlterField(
            model_name='materialstock',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material'),
        ),
        migrations.AlterField(
            model_name='materialstock',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='wb_article',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='productbom',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material'),
        ),
        migrations.AlterField(
            model_name='productbom',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='productbom',
            name='qty_per_unit',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AlterField(
            model_name='production',
            name='produced_qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='productionmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material'),
        ),
        migrations.AlterField(
            model_name='productionmaterial',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.production'),
        ),
        migrations.AlterField(
            model_name='productionmaterial',
            name='quantity_used',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipmentlogistics',
            name='carrier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipmentlogistics',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipmentlogistics',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.wbshipment'),
        ),
        migrations.AlterField(
            model_name='shipmentlogistics',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wbshipment',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wbshipment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='wbshipment',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_from', to='core.location'),
        ),
        migrations.AlterField(
            model_name='wbshipment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='wbshipment',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wbshipment',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_to', to='core.location'),
        ),
        migrations.AlterField(
            model_name='wbshipment',
            name='wb_shipment_number',
            field=models.CharField(max_length=50),
        ),
    ]
